sudo: false
language: node_js
node_js:
  - "8"

cache: yarn

# enable building the "speaker" package and puppeteer
# https://github.com/TooTallNate/node-speaker/blob/master/.travis.yml#L3
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libasound2-dev

install:
  - yarn install --ignore-optional # Ignore the speaker
script:
  - npm run-script ci
