sudo: false
language: node_js
node_js:
  - "8"

cache: yarn

# enable building the "speaker" package
# https://github.com/TooTallNate/node-speaker/blob/master/.travis.yml#L3
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libasound2-dev

script:
  - npm run-script test
  - npm run-script ci-codecov